### ISSUE TITLE
CrossReference: Tags used in captions don't work any more

### ISSUE THREAD

**Issue by Schlumpfpapa** [gallandarakhneorg/mediawiki-plugins#2]
Wenn using tags like `<ref>...</ref>` oder `<nowiki>...</nowiki>` inside a caption, garbled output like `?'"UNIQ--ref-00000024-QINU"'?` is displayed instead.

Possible fix may be included in this article:
https://www.mediawiki.org/wiki/QINU_fix

**Comment by Schlumpfpapa** [comment]
Sorry, problem seems to be not caused by CrossReference.

**Comment by Schlumpfpapa** [comment]
I stripped down the problem to this:

This code works:
```
This is a reference to the following figure: <xr id="test1"/>
<figure id=test1><caption>Test a<nowiki>=</nowiki>b</caption></figure>

```

This should be identical but does not work:
```
This is a reference to the following figure: <xr id="test1"/>
{{#tag:figure|<caption>Test a<nowiki>=</nowiki>b</caption>|id=test1}}
```

unfortunately the latter is often needed when defining Templates using CrossReferenced code.

In the above example `<nowiki>=</nowiki>` is not really needed, but there are use cases that require `<nowiki>` around "=", and other tags like `<ref>` cause the above error too.

**Comment by gallandarakhneorg** [comment]
I have no way to test on the latest versions of Mediawiki because I cannot upgrade my server to a newer version.
You should provide a bug fix through the pull request mechanism for newer versions.

**Comment by Schlumpfpapa** [comment]
Unfortunately my knowledge of php and mediawiki APIs is not sufficient for that, sorry.
BTW: Problem occurs on MediaWiki 1.27 (current long term support version)

**Comment by gallandarakhneorg** [comment]
The web server of my laboratory is running MediaWiki 1.15 and we have no plan for upgrading to a newer Mediawiki technology. We have preferred to move to Java technologies.

**Comment by Schlumpfpapa** [comment]
Please leave the issue open, perhaps some other user stumbles across the same problem and finds a solution. Additionally you could assign the label „help wanted“ to it.

Thanks for creating this plugin, it means a lot to our work.

**Comment by gallandarakhneorg** [comment]
See PR #5.
