### ISSUE TITLE
Divide mediawiki-plugins into separate repositories?

### ISSUE THREAD

**Issue by staspika** [gallandarakhneorg/mediawiki-plugins#6]
Would it not be nice to divide these extensions into separate repositories (taking care of all history, as described in https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/)? Or is there any particular reason to keep them together as a single project? I, for one, can not see how they are interdependent, and I would appreciate to be able to fork only the CrossReference, which is the only one I use and contribute to :)

**Comment by gallandarakhneorg** [comment]
Initially, all the mediawiki plugins are involved into a single website development project.
I have no strong objection to split the project and links the created repostories together.

**Comment by staspika** [comment]
I personally would appreciate if you did so, Stéphane!

**Comment by gallandarakhneorg** [comment]
The new repository is [gallandarakhneorg/mediawiki-crossreference](/gallandarakhneorg/mediawiki-crossreference).

The rest of the repository will not change until someone ask to externalize a specific plugin.
This repository will still have a pointer to the CrossReference repository as a [submodule](https://github.com/blog/2104-working-with-submodules).
